order:
  - 1-Pytorch-Intro
  - 2-Gradient-Descent
  - 3-Backpropagation
  - 4-Simple-Network
  - 5-Feedforward-NN
  - 6-Convolutional-NN
  - 7-Segmentation
  - 8-Detection
  - 9-Word2Vec
  - 10-Transformer
